### PR TITLE
JSDoc for `Client` and `CabalDetails`

### PR DESCRIPTION
**Pull request by fenwick67**
See #18 

I wasn't sure about `ChannelDetails` since there wasn't any existing documentation on it, so I left it alone.

npm task `doc` will generate documentation again.

### CODE REVIEW

**Comment by cblgh** [comment]
@fenwick67 woah thank you!!

i'll leave a review in a minute

**Comment by cblgh** [comment]
wow that changes requested symbol looks really angry 

image

**Comment by fenwick67** [comment]
Cool, I'll look at each of these and see how hard it is to get them changed with `jsdoc-to-markdown`. At first glance I think at least some of this can be done with custom handlebars templates.

**Comment by fenwick67** [comment]
Aaah I accidentally squashed too many commits. But there you go, that should resolve those issues.

**Comment by cblgh** [comment]
this is perfect! thank you a ton @fenwick67!!!

**Comment by noffle** [comment]
I just realized I wasn't watching this repo.

Wow! @fenwick67! Thank you so much for the docs :heart:

**Pull request merged**
